name: Test Project
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            # checkout code
            - name: Get code
              uses: actions/checkout@v3
            # nodejs already installed on ubuntu-latest
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            # install all node dependencies
            - name: Install dependencies
              run: npm ci
            # run tests
            - name: Run tests
              run: npm test